# =============================================================================
# Google Drive Folder Structure
# =============================================================================
# Onomancer Bot - Google Workspace Foundation
# Sprint 1 - Task 1.4: Terraform Folder Structure
#
# Folder Hierarchy:
# /The Honey Jar (root)
#   /Products
#     /MiBera
#       /PRD
#         /Executive Summaries
#           /Leadership
#           /Product
#           /Marketing
#           /DevRel
#       /SDD
#         /Executive Summaries
#           /Leadership
#           /Product
#           /Marketing
#           /DevRel
#       /Sprints
#         (Sprint folders created dynamically)
#       /Audits
#         (Audit folders created dynamically)
#     /FatBera (same structure)
#     /Interpol (same structure)
#     /Set & Forgetti (same structure)
#   /Shared
#     /Weekly Digests
#     /Templates
#
# NOTE: Google Drive API doesn't have a native Terraform provider for folders.
# This module uses null_resource with local-exec provisioners to create
# folders via the Google Drive API. In production, consider using:
# 1. A custom Terraform provider for Google Drive
# 2. A separate setup script that runs after terraform apply
# 3. Pulumi or other IaC tools with better Google Workspace support
# =============================================================================

# -----------------------------------------------------------------------------
# Local Variables for Folder Structure
# -----------------------------------------------------------------------------

locals {
  # Document types that need executive summary subfolders
  document_types = ["PRD", "SDD", "Sprints", "Audits"]

  # Generate flat list of all folders to create
  # This creates a comprehensive folder mapping for the null_resource

  product_folders = flatten([
    for product in var.products : [
      {
        name   = product
        parent = "products"
        path   = "/Products/${product}"
        type   = "product"
      }
    ]
  ])

  # Document type folders within each product
  document_folders = flatten([
    for product in var.products : [
      for doc_type in local.document_types : {
        name   = doc_type
        parent = product
        path   = "/Products/${product}/${doc_type}"
        type   = "document_type"
      }
    ]
  ])

  # Executive Summary folders within each document type
  exec_summary_folders = flatten([
    for product in var.products : [
      for doc_type in local.document_types : {
        name   = "Executive Summaries"
        parent = "${product}/${doc_type}"
        path   = "/Products/${product}/${doc_type}/Executive Summaries"
        type   = "exec_summary"
      }
    ]
  ])

  # Persona folders within each Executive Summary folder
  persona_folders = flatten([
    for product in var.products : [
      for doc_type in local.document_types : [
        for persona in var.personas : {
          name   = persona
          parent = "${product}/${doc_type}/Executive Summaries"
          path   = "/Products/${product}/${doc_type}/Executive Summaries/${persona}"
          type   = "persona"
        }
      ]
    ]
  ])

  # Shared folders
  shared_folders = [
    {
      name   = "Weekly Digests"
      parent = "shared"
      path   = "/Shared/Weekly Digests"
      type   = "shared"
    },
    {
      name   = "Templates"
      parent = "shared"
      path   = "/Shared/Templates"
      type   = "shared"
    }
  ]

  # Complete folder structure as a map for JSON export
  folder_structure = {
    root = {
      name = var.root_folder_name
      path = "/"
    }
    products = {
      name = "Products"
      path = "/Products"
    }
    shared = {
      name = "Shared"
      path = "/Shared"
    }
    product_folders       = local.product_folders
    document_folders      = local.document_folders
    exec_summary_folders  = local.exec_summary_folders
    persona_folders       = local.persona_folders
    shared_folders        = local.shared_folders
  }
}

# -----------------------------------------------------------------------------
# Google Drive Folder Creation Script
# -----------------------------------------------------------------------------
# Since Terraform doesn't have native Google Drive folder support,
# we generate a setup script that creates the folder structure.
# This script uses the Google Drive API via Node.js googleapis library.

resource "local_file" "folder_setup_script" {
  filename = "${path.root}/../scripts/setup-drive-folders.ts"
  content  = <<-EOF
/**
 * Google Drive Folder Setup Script
 * =================================
 * Generated by Terraform - DO NOT EDIT MANUALLY
 *
 * This script creates the Google Drive folder structure for Onomancer Bot.
 * Run with: npx ts-node scripts/setup-drive-folders.ts
 *
 * Prerequisites:
 * - Service account key at secrets/google-service-account-key.json
 * - Service account has Drive API permissions
 * - googleapis package installed
 */

import { google } from 'googleapis';
import * as fs from 'fs';
import * as path from 'path';

// Folder structure configuration
const config = {
  rootFolderName: '${var.root_folder_name}',
  products: ${jsonencode(var.products)},
  documentTypes: ['PRD', 'SDD', 'Sprints', 'Audits'],
  personas: ${jsonencode(var.personas)},
  environment: '${var.environment}'
};

// Service account authentication
async function authenticate() {
  const keyPath = path.join(__dirname, '../secrets/google-service-account-key.json');

  if (!fs.existsSync(keyPath)) {
    throw new Error(`Service account key not found at $${keyPath}. Run terraform apply first.`);
  }

  const auth = new google.auth.GoogleAuth({
    keyFile: keyPath,
    scopes: [
      'https://www.googleapis.com/auth/drive',
      'https://www.googleapis.com/auth/drive.file'
    ]
  });

  return auth;
}

// Create a folder in Google Drive
async function createFolder(
  drive: any,
  name: string,
  parentId?: string
): Promise<{ id: string; name: string }> {
  const fileMetadata: any = {
    name,
    mimeType: 'application/vnd.google-apps.folder'
  };

  if (parentId) {
    fileMetadata.parents = [parentId];
  }

  const response = await drive.files.create({
    requestBody: fileMetadata,
    fields: 'id, name'
  });

  console.log(`Created folder: $${name} (ID: $${response.data.id})`);
  return { id: response.data.id, name: response.data.name };
}

// Escape special characters in folder names for Drive API queries
function escapeFolderName(name: string): string {
  // Escape single quotes and backslashes for Drive API query syntax
  return name.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

// Check if folder exists
async function findFolder(
  drive: any,
  name: string,
  parentId?: string
): Promise<string | null> {
  const escapedName = escapeFolderName(name);
  let query = `name='$${escapedName}' and mimeType='application/vnd.google-apps.folder' and trashed=false`;
  if (parentId) {
    query += ` and '$${parentId}' in parents`;
  }

  const response = await drive.files.list({
    q: query,
    fields: 'files(id, name)',
    spaces: 'drive'
  });

  if (response.data.files && response.data.files.length > 0) {
    return response.data.files[0].id;
  }
  return null;
}

// Get or create folder (idempotent)
async function getOrCreateFolder(
  drive: any,
  name: string,
  parentId?: string
): Promise<string> {
  const existingId = await findFolder(drive, name, parentId);
  if (existingId) {
    console.log(`Folder already exists: $${name} (ID: $${existingId})`);
    return existingId;
  }
  const newFolder = await createFolder(drive, name, parentId);
  return newFolder.id;
}

// Main setup function
async function setupFolderStructure() {
  console.log('Setting up Google Drive folder structure...');
  console.log('Environment:', config.environment);
  console.log('');

  const auth = await authenticate();
  const drive = google.drive({ version: 'v3', auth });

  // Track folder IDs for JSON output
  const folderIds: Record<string, string> = {};

  // Create root folder
  const rootId = await getOrCreateFolder(drive, config.rootFolderName);
  folderIds['root'] = rootId;

  // Create /Products folder
  const productsId = await getOrCreateFolder(drive, 'Products', rootId);
  folderIds['products'] = productsId;

  // Create /Shared folder
  const sharedId = await getOrCreateFolder(drive, 'Shared', rootId);
  folderIds['shared'] = sharedId;

  // Create shared subfolders
  const weeklyDigestsId = await getOrCreateFolder(drive, 'Weekly Digests', sharedId);
  folderIds['weekly_digests'] = weeklyDigestsId;

  const templatesId = await getOrCreateFolder(drive, 'Templates', sharedId);
  folderIds['templates'] = templatesId;

  // Create product folder structures
  for (const product of config.products) {
    const productKey = product.toLowerCase().replace(/[^a-z0-9]/g, '_');

    // Create product folder
    const productFolderId = await getOrCreateFolder(drive, product, productsId);
    folderIds[`product_$${productKey}`] = productFolderId;

    // Create document type folders
    for (const docType of config.documentTypes) {
      const docTypeKey = docType.toLowerCase();
      const docTypeFolderId = await getOrCreateFolder(drive, docType, productFolderId);
      folderIds[`$${productKey}_$${docTypeKey}`] = docTypeFolderId;

      // Create Executive Summaries folder
      const execSummaryId = await getOrCreateFolder(drive, 'Executive Summaries', docTypeFolderId);
      folderIds[`$${productKey}_$${docTypeKey}_exec`] = execSummaryId;

      // Create persona subfolders
      for (const persona of config.personas) {
        const personaKey = persona.toLowerCase();
        const personaFolderId = await getOrCreateFolder(drive, persona, execSummaryId);
        folderIds[`$${productKey}_$${docTypeKey}_$${personaKey}`] = personaFolderId;
      }
    }
  }

  // Save folder IDs to JSON file for bot runtime use
  const outputPath = path.join(__dirname, '../config/folder-ids.json');
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, JSON.stringify(folderIds, null, 2));
  console.log('');
  console.log(`Folder IDs saved to: $${outputPath}`);

  // Print summary
  console.log('');
  console.log('=== Folder Structure Created ===');
  console.log(`Root: $${config.rootFolderName} (ID: $${rootId})`);
  console.log(`Products: $${config.products.length} products`);
  console.log(`Document Types: $${config.documentTypes.length} types per product`);
  console.log(`Personas: $${config.personas.length} personas per document type`);
  console.log(`Total folders created: $${Object.keys(folderIds).length}`);
}

// Run setup
setupFolderStructure()
  .then(() => {
    console.log('');
    console.log('Setup complete!');
    process.exit(0);
  })
  .catch((error) => {
    console.error('Setup failed:', error);
    process.exit(1);
  });
EOF

  depends_on = [
    local_sensitive_file.service_account_key
  ]
}

# -----------------------------------------------------------------------------
# Folder Structure JSON Configuration
# -----------------------------------------------------------------------------
# This generates a JSON configuration file that defines the expected
# folder structure. Used by the bot for folder path resolution.

resource "local_file" "folder_config" {
  filename = "${path.root}/../config/folder-structure.json"
  content = jsonencode({
    version          = "1.0.0"
    environment      = var.environment
    organization     = var.organization_name
    root_folder_name = var.root_folder_name
    products         = var.products
    document_types   = local.document_types
    personas         = var.personas
    structure = {
      root = {
        name     = var.root_folder_name
        path     = "/"
        children = ["Products", "Shared"]
      }
      products = {
        name     = "Products"
        path     = "/Products"
        children = var.products
      }
      shared = {
        name     = "Shared"
        path     = "/Shared"
        children = ["Weekly Digests", "Templates"]
      }
    }
    path_templates = {
      product_root     = "/Products/{product}"
      document_type    = "/Products/{product}/{documentType}"
      exec_summaries   = "/Products/{product}/{documentType}/Executive Summaries"
      persona          = "/Products/{product}/{documentType}/Executive Summaries/{persona}"
      weekly_digest    = "/Shared/Weekly Digests/{date}"
      sprint           = "/Products/{product}/Sprints/{sprintId}"
      sprint_persona   = "/Products/{product}/Sprints/{sprintId}/Executive Summaries/{persona}"
      audit            = "/Products/{product}/Audits/{auditId}"
      audit_persona    = "/Products/{product}/Audits/{auditId}/Executive Summaries/{persona}"
    }
  })

  depends_on = [
    google_service_account.onomancer_bot
  ]
}
