# =============================================================================
# Workspace Module - Main Configuration
# =============================================================================
# Onomancer Bot - Google Workspace Foundation
# Sprint 1 - Task 1.3: Service Account & API Credentials
# =============================================================================

# -----------------------------------------------------------------------------
# Enable Required Google Cloud APIs
# -----------------------------------------------------------------------------

resource "google_project_service" "drive_api" {
  project            = var.project_id
  service            = "drive.googleapis.com"
  disable_on_destroy = false
}

resource "google_project_service" "docs_api" {
  project            = var.project_id
  service            = "docs.googleapis.com"
  disable_on_destroy = false
}

resource "google_project_service" "admin_api" {
  project            = var.project_id
  service            = "admin.googleapis.com"
  disable_on_destroy = false
}

resource "google_project_service" "iam_api" {
  project            = var.project_id
  service            = "iam.googleapis.com"
  disable_on_destroy = false
}

resource "google_project_service" "cloudresourcemanager_api" {
  project            = var.project_id
  service            = "cloudresourcemanager.googleapis.com"
  disable_on_destroy = false
}

# -----------------------------------------------------------------------------
# Service Account for Onomancer Bot
# -----------------------------------------------------------------------------

resource "google_service_account" "onomancer_bot" {
  account_id   = var.service_account_id
  display_name = var.service_account_display_name
  description  = "Service account for Onomancer Bot to access Google Drive and Docs APIs"
  project      = var.project_id

  depends_on = [
    google_project_service.iam_api
  ]
}

# Grant the service account necessary IAM roles at project level
# IAM Role: roles/drive.admin
# Rationale: Bot needs to create folders, manage permissions, and organize
# documents across the entire product hierarchy (~84 folders). roles/drive.file
# is insufficient as it only allows file-level operations on files the service
# account creates - it cannot create folders in shared drives or manage permissions.
resource "google_project_iam_member" "drive_admin" {
  project = var.project_id
  role    = "roles/drive.admin"
  member  = "serviceAccount:${google_service_account.onomancer_bot.email}"

  depends_on = [google_project_service.drive_api]
}

# Grant Google Docs API access
# Required for: Reading/writing Google Docs as part of the transformation pipeline
resource "google_project_iam_member" "docs_editor" {
  project = var.project_id
  role    = "roles/docs.editor"
  member  = "serviceAccount:${google_service_account.onomancer_bot.email}"

  depends_on = [google_project_service.docs_api]
}

# -----------------------------------------------------------------------------
# Service Account Key
# -----------------------------------------------------------------------------
# WARNING: Service account keys are sensitive! The key is stored in
# Terraform state. Consider using Workload Identity for production.

resource "google_service_account_key" "onomancer_bot_key" {
  service_account_id = google_service_account.onomancer_bot.name
  private_key_type   = "TYPE_GOOGLE_CREDENTIALS_FILE"
}

# Store the service account key in a local file for development
# SECURITY: This file should be gitignored and have restrictive permissions
resource "local_sensitive_file" "service_account_key" {
  content         = base64decode(google_service_account_key.onomancer_bot_key.private_key)
  filename        = "${path.root}/../secrets/google-service-account-key.json"
  file_permission = "0600"
}

# Generate .env.local file with credentials for bot integration
# This provides environment variables in the format expected by the bot application
resource "local_sensitive_file" "env_local" {
  filename        = "${path.root}/../secrets/.env.local"
  file_permission = "0600"
  content         = <<-EOT
# Generated by Terraform - DO NOT EDIT MANUALLY
# Service Account Credentials for Onomancer Bot
# Generated: ${timestamp()}

GOOGLE_SERVICE_ACCOUNT_EMAIL="${google_service_account.onomancer_bot.email}"
GOOGLE_SERVICE_ACCOUNT_KEY_PATH="${abspath("${path.root}/../secrets/google-service-account-key.json")}"
EOT

  depends_on = [local_sensitive_file.service_account_key]
}

# -----------------------------------------------------------------------------
# Data Sources
# -----------------------------------------------------------------------------

data "google_project" "current" {
  project_id = var.project_id
}
