# =============================================================================
# Workspace Module Outputs
# =============================================================================
# Onomancer Bot - Google Workspace Foundation
# Sprint 1 - Tasks 1.3, 1.4, 1.5
# =============================================================================

# -----------------------------------------------------------------------------
# Service Account Outputs
# -----------------------------------------------------------------------------

output "service_account_email" {
  description = "Email address of the Onomancer Bot service account"
  value       = google_service_account.onomancer_bot.email
}

output "service_account_id" {
  description = "Unique ID of the service account"
  value       = google_service_account.onomancer_bot.unique_id
}

output "service_account_name" {
  description = "Full name of the service account resource"
  value       = google_service_account.onomancer_bot.name
}

output "service_account_key_name" {
  description = "Name of the service account key (key ID)"
  value       = google_service_account_key.onomancer_bot_key.name
  sensitive   = true
}

# -----------------------------------------------------------------------------
# API Enablement Outputs
# -----------------------------------------------------------------------------

output "enabled_apis" {
  description = "List of enabled Google Cloud APIs"
  value = [
    google_project_service.drive_api.service,
    google_project_service.docs_api.service,
    google_project_service.admin_api.service,
    google_project_service.iam_api.service,
    google_project_service.cloudresourcemanager_api.service
  ]
}

# -----------------------------------------------------------------------------
# Folder Structure Outputs
# -----------------------------------------------------------------------------
# NOTE: Actual folder IDs are generated by the setup script at runtime.
# These outputs provide the expected folder structure configuration.

output "root_folder_id" {
  description = "Placeholder - actual ID set after running setup-drive-folders.ts"
  value       = "run-setup-drive-folders-script"
}

output "products_folder_id" {
  description = "Placeholder - actual ID set after running setup-drive-folders.ts"
  value       = "run-setup-drive-folders-script"
}

output "shared_folder_id" {
  description = "Placeholder - actual ID set after running setup-drive-folders.ts"
  value       = "run-setup-drive-folders-script"
}

output "product_folder_ids" {
  description = "Map of product names - actual IDs in config/folder-ids.json"
  value = {
    for product in var.products :
    product => "run-setup-drive-folders-script"
  }
}

output "weekly_digests_folder_id" {
  description = "Placeholder - actual ID set after running setup-drive-folders.ts"
  value       = "run-setup-drive-folders-script"
}

output "templates_folder_id" {
  description = "Placeholder - actual ID set after running setup-drive-folders.ts"
  value       = "run-setup-drive-folders-script"
}

output "folder_structure_json" {
  description = "Path to the folder structure JSON configuration file"
  value       = "${path.root}/../config/folder-structure.json"
}

# -----------------------------------------------------------------------------
# Stakeholder Group Outputs
# -----------------------------------------------------------------------------

output "stakeholder_group_emails" {
  description = "Map of stakeholder group names to their email addresses"
  value       = local.stakeholder_emails
}

# -----------------------------------------------------------------------------
# Script Paths
# -----------------------------------------------------------------------------

output "folder_setup_script_path" {
  description = "Path to the folder setup script"
  value       = "${path.root}/../scripts/setup-drive-folders.ts"
}

output "permissions_setup_script_path" {
  description = "Path to the permissions setup script"
  value       = "${path.root}/../scripts/setup-drive-permissions.ts"
}

output "groups_config_path" {
  description = "Path to the Google Groups configuration file"
  value       = "${path.root}/../config/google-groups.json"
}
