# =============================================================================
# Stakeholder Permissions Configuration
# =============================================================================
# Onomancer Bot - Google Workspace Foundation
# Sprint 1 - Task 1.5: Stakeholder Permissions
#
# Permission Model:
# - Leadership Group: Read access to all Executive Summaries/Leadership folders
# - Product Group: Read access to PRD, SDD, Sprint Reports
# - Marketing Group: Read access to Marketing summaries
# - DevRel Group: Read access to DevRel summaries and technical docs
# - Developers Group: Read/Write access to all folders
# - Service Account: Full access (Owner) to all folders
#
# NOTE: Google Workspace Groups must be created manually in Google Admin Console
# as Terraform support for Google Workspace Groups is limited.
# This module generates a permissions setup script instead.
# =============================================================================

# -----------------------------------------------------------------------------
# Local Variables for Permission Mapping
# -----------------------------------------------------------------------------

locals {
  # Generate stakeholder group emails
  stakeholder_emails = {
    for key, group in var.stakeholder_groups :
    key => "${group.name}@${var.domain}"
  }

  # Permission mapping: folder path pattern -> allowed groups
  permission_rules = {
    # Leadership summaries - Leadership can read
    leadership_summaries = {
      path_pattern = "/Products/*/*/Executive Summaries/Leadership/*"
      groups       = ["leadership", "developers"]
      role         = "reader"
    }
    # Product summaries - Product team can read
    product_summaries = {
      path_pattern = "/Products/*/*/Executive Summaries/Product/*"
      groups       = ["product", "developers"]
      role         = "reader"
    }
    # Marketing summaries - Marketing can read
    marketing_summaries = {
      path_pattern = "/Products/*/*/Executive Summaries/Marketing/*"
      groups       = ["marketing", "developers"]
      role         = "reader"
    }
    # DevRel summaries - DevRel can read
    devrel_summaries = {
      path_pattern = "/Products/*/*/Executive Summaries/DevRel/*"
      groups       = ["devrel", "developers"]
      role         = "reader"
    }
    # All PRD folders - Product can read
    prd_folders = {
      path_pattern = "/Products/*/PRD/*"
      groups       = ["product", "leadership", "developers"]
      role         = "reader"
    }
    # All SDD folders - Product and DevRel can read
    sdd_folders = {
      path_pattern = "/Products/*/SDD/*"
      groups       = ["product", "devrel", "developers"]
      role         = "reader"
    }
    # Sprint folders - All stakeholders can read
    sprint_folders = {
      path_pattern = "/Products/*/Sprints/*"
      groups       = ["leadership", "product", "marketing", "devrel", "developers"]
      role         = "reader"
    }
    # Audit folders - Leadership and DevRel can read
    audit_folders = {
      path_pattern = "/Products/*/Audits/*"
      groups       = ["leadership", "devrel", "developers"]
      role         = "reader"
    }
    # Weekly digests - All stakeholders can read
    weekly_digests = {
      path_pattern = "/Shared/Weekly Digests/*"
      groups       = ["leadership", "product", "marketing", "devrel", "developers"]
      role         = "reader"
    }
    # Templates - Developers only
    templates = {
      path_pattern = "/Shared/Templates/*"
      groups       = ["developers"]
      role         = "writer"
    }
  }
}

# -----------------------------------------------------------------------------
# Permissions Setup Script
# -----------------------------------------------------------------------------
# This generates a script to configure Google Drive permissions.
# Run after creating folder structure with setup-drive-folders.ts

resource "local_file" "permissions_setup_script" {
  filename = "${path.root}/../scripts/setup-drive-permissions.ts"
  content  = <<-EOF
/**
 * Google Drive Permissions Setup Script
 * ======================================
 * Generated by Terraform - DO NOT EDIT MANUALLY
 *
 * This script configures permissions on Google Drive folders.
 * Run with: npx ts-node scripts/setup-drive-permissions.ts
 *
 * Prerequisites:
 * - Folder structure created (run setup-drive-folders.ts first)
 * - Google Workspace Groups created in Admin Console
 * - folder-ids.json exists in config/
 */

import { google } from 'googleapis';
import * as fs from 'fs';
import * as path from 'path';

// Permission configuration
const config = {
  domain: '${var.domain}',
  serviceAccountEmail: '${google_service_account.onomancer_bot.email}',
  stakeholderGroups: ${jsonencode(local.stakeholder_emails)},
  permissionRules: ${jsonencode(local.permission_rules)}
};

// Google Drive role mapping
const roleMapping: Record<string, string> = {
  'reader': 'reader',
  'writer': 'writer',
  'owner': 'owner'
};

// Valid role values for validation
const validRoles = Object.keys(roleMapping);

// Validate role value and throw if invalid
function validateRole(role: string): void {
  if (!roleMapping[role]) {
    throw new Error(
      \`Invalid role: "\$${role}". Valid roles are: \$${validRoles.join(', ')}. ` +
      \`Check your permission configuration for typos.\`
    );
  }
}

// Service account authentication
async function authenticate() {
  const keyPath = path.join(__dirname, '../secrets/google-service-account-key.json');

  if (!fs.existsSync(keyPath)) {
    throw new Error(\`Service account key not found at \$${keyPath}\`);
  }

  const auth = new google.auth.GoogleAuth({
    keyFile: keyPath,
    scopes: [
      'https://www.googleapis.com/auth/drive',
      'https://www.googleapis.com/auth/drive.file'
    ]
  });

  return auth;
}

// Load folder IDs from config
function loadFolderIds(): Record<string, string> {
  const configPath = path.join(__dirname, '../config/folder-ids.json');

  if (!fs.existsSync(configPath)) {
    throw new Error(\`Folder IDs not found at \$${configPath}. Run setup-drive-folders.ts first.\`);
  }

  return JSON.parse(fs.readFileSync(configPath, 'utf-8'));
}

// Set permission on a folder
async function setPermission(
  drive: any,
  folderId: string,
  email: string,
  role: string,
  type: string = 'group'
): Promise<boolean> {
  // Validate role before making API call - fail fast on typos
  validateRole(role);

  try {
    await drive.permissions.create({
      fileId: folderId,
      requestBody: {
        type: type,
        role: roleMapping[role],
        emailAddress: email
      },
      sendNotificationEmail: false,
      fields: 'id'
    });
    console.log(\`  ✓ Set \$${role} permission for \$${email}\`);
    return true;
  } catch (error: any) {
    if (error.code === 400 && error.message.includes('already has access')) {
      console.log(\`  ○ Permission already exists for \$${email}\`);
      return true;
    } else {
      console.error(\`  ✗ Failed to set permission for \$${email}: \$${error.message}\`);
      return false;
    }
  }
}

// Main setup function
async function setupPermissions() {
  console.log('Setting up Google Drive permissions...');
  console.log('Domain:', config.domain);
  console.log('');

  const auth = await authenticate();
  const drive = google.drive({ version: 'v3', auth });
  const folderIds = loadFolderIds();

  // Track permission results for summary
  let permissionsSet = 0;
  let permissionsFailed = 0;
  let foldersProcessed = 0;

  // First, ensure service account has owner access to all folders
  console.log('Setting service account owner permissions...');
  for (const [key, folderId] of Object.entries(folderIds)) {
    console.log(\`Folder: \$${key}\`);
    foldersProcessed++;
    const success = await setPermission(
      drive,
      folderId,
      config.serviceAccountEmail,
      'owner',
      'user'
    );
    if (success) permissionsSet++; else permissionsFailed++;
  }

  console.log('');
  console.log('Setting stakeholder group permissions...');

  // Helper to track permission results
  async function trackPermission(
    drive: any,
    folderId: string,
    email: string,
    role: string,
    type: string = 'group'
  ): Promise<void> {
    const success = await setPermission(drive, folderId, email, role, type);
    if (success) permissionsSet++; else permissionsFailed++;
  }

  // Set permissions based on folder naming patterns
  for (const [key, folderId] of Object.entries(folderIds)) {
    console.log(\`Folder: \$${key}\`);

    // Developers group gets access to all folders
    if (config.stakeholderGroups.developers) {
      await trackPermission(
        drive,
        folderId,
        config.stakeholderGroups.developers,
        'writer',
        'group'
      );
    }

    // Apply persona-specific permissions based on folder key patterns
    if (key.includes('_leadership')) {
      if (config.stakeholderGroups.leadership) {
        await trackPermission(
          drive,
          folderId,
          config.stakeholderGroups.leadership,
          'reader',
          'group'
        );
      }
    }
    if (key.includes('_product')) {
      if (config.stakeholderGroups.product) {
        await trackPermission(
          drive,
          folderId,
          config.stakeholderGroups.product,
          'reader',
          'group'
        );
      }
    }
    if (key.includes('_marketing')) {
      if (config.stakeholderGroups.marketing) {
        await trackPermission(
          drive,
          folderId,
          config.stakeholderGroups.marketing,
          'reader',
          'group'
        );
      }
    }
    if (key.includes('_devrel')) {
      if (config.stakeholderGroups.devrel) {
        await trackPermission(
          drive,
          folderId,
          config.stakeholderGroups.devrel,
          'reader',
          'group'
        );
      }
    }

    // PRD folders - Leadership and Product
    if (key.includes('_prd') && !key.includes('_exec')) {
      if (config.stakeholderGroups.leadership) {
        await trackPermission(drive, folderId, config.stakeholderGroups.leadership, 'reader', 'group');
      }
      if (config.stakeholderGroups.product) {
        await trackPermission(drive, folderId, config.stakeholderGroups.product, 'reader', 'group');
      }
    }

    // SDD folders - Product and DevRel
    if (key.includes('_sdd') && !key.includes('_exec')) {
      if (config.stakeholderGroups.product) {
        await trackPermission(drive, folderId, config.stakeholderGroups.product, 'reader', 'group');
      }
      if (config.stakeholderGroups.devrel) {
        await trackPermission(drive, folderId, config.stakeholderGroups.devrel, 'reader', 'group');
      }
    }

    // Sprint folders - All stakeholders
    if (key.includes('_sprints') && !key.includes('_exec')) {
      for (const [groupKey, email] of Object.entries(config.stakeholderGroups)) {
        if (groupKey !== 'developers') {
          await trackPermission(drive, folderId, email, 'reader', 'group');
        }
      }
    }

    // Audit folders - Leadership and DevRel
    if (key.includes('_audits') && !key.includes('_exec')) {
      if (config.stakeholderGroups.leadership) {
        await trackPermission(drive, folderId, config.stakeholderGroups.leadership, 'reader', 'group');
      }
      if (config.stakeholderGroups.devrel) {
        await trackPermission(drive, folderId, config.stakeholderGroups.devrel, 'reader', 'group');
      }
    }

    // Weekly digests - All stakeholders
    if (key === 'weekly_digests') {
      for (const [groupKey, email] of Object.entries(config.stakeholderGroups)) {
        if (groupKey !== 'developers') {
          await trackPermission(drive, folderId, email, 'reader', 'group');
        }
      }
    }
  }

  // Disable external sharing on root folder (inherits to children)
  console.log('');
  console.log('Disabling external sharing on root folder...');
  try {
    // Note: This requires domain-wide delegation or admin access
    // May need to be done manually in Google Admin Console
    console.log('NOTE: External sharing restrictions should be configured in Google Admin Console');
    console.log('Navigate to: Admin Console > Apps > Google Workspace > Drive and Docs > Sharing Settings');
  } catch (error) {
    console.warn('Could not configure sharing settings. Configure manually in Admin Console.');
  }

  // Print summary with success/failure counts
  console.log('');
  console.log('=== Permissions Setup Summary ===');
  console.log(\`Folders processed: \$${foldersProcessed}\`);
  console.log(\`Permissions set successfully: \$${permissionsSet}\`);
  console.log(\`Permissions failed: \$${permissionsFailed}\`);

  if (permissionsFailed > 0) {
    console.log('');
    console.log('⚠️  WARNING: Some permissions failed to set.');
    console.log('   Review the errors above and ensure:');
    console.log('   - Google Groups exist in Admin Console');
    console.log('   - Service account has sufficient permissions');
    console.log('   - Group email addresses are correct');
  } else {
    console.log('');
    console.log('✓ All permissions set successfully!');
  }

  console.log('');
  console.log('IMPORTANT: Verify the following in Google Admin Console:');
  console.log('1. Google Groups exist for all stakeholder groups');
  console.log('2. External sharing is disabled for the organization');
  console.log('3. Link sharing requires organization membership');

  // Return exit code based on failures
  return permissionsFailed === 0;
}

// Run setup
setupPermissions()
  .then((success) => {
    console.log('');
    if (success) {
      console.log('Permissions setup complete!');
      process.exit(0);
    } else {
      console.log('Permissions setup completed with errors. See above for details.');
      process.exit(1);
    }
  })
  .catch((error) => {
    console.error('Permissions setup failed:', error);
    process.exit(1);
  });
EOF

  depends_on = [
    local_file.folder_setup_script
  ]
}

# -----------------------------------------------------------------------------
# Google Workspace Groups Configuration (Documentation)
# -----------------------------------------------------------------------------
# Google Groups should be created manually in Google Admin Console.
# This generates a configuration file documenting required groups.

resource "local_file" "groups_config" {
  filename = "${path.root}/../config/google-groups.json"
  content = jsonencode({
    version     = "1.0.0"
    environment = var.environment
    domain      = var.domain
    groups = {
      for key, group in var.stakeholder_groups :
      key => {
        email       = "${group.name}@${var.domain}"
        name        = title(group.name)
        description = group.description
        access      = group.access
      }
    }
    setup_instructions = [
      "1. Log into Google Admin Console (admin.google.com)",
      "2. Navigate to Directory > Groups",
      "3. Create each group listed above",
      "4. Add appropriate members to each group",
      "5. Run setup-drive-permissions.ts to apply folder permissions"
    ]
  })
}
